### ISSUE TITLE
Not compatible with labels for LTO7

### ISSUE THREAD

**Issue by ymulleneers** [markusberg/barcode-php#3]
This code has no possibility to be used with LTO-7 tapes.

1. There is no LTO-7 choices
2. It seems that the sticker get printed but not read by the tape loader, contrary to https://tapelabel.de/ .

**Comment by markusberg** [comment]
Oh, wow. I didn't even remember this old repo. I haven't touched it since 2015. I have an updated version here:
https://kelvin.nu/barcode

I haven't gotten around to publishing the source code to it though.
